name = "kritha-globally-dynamic"
main = "workers/globally-dynamic.js"
compatibility_date = "2026-09-17"
preview_urls= true
workers_dev = true

[assets]
directory = "./dist/globally-dynamic/release"
binding = "ASSETS"
run_worker_first = true
