plugins {
    id("com.android.dynamic-feature")
    id("org.jetbrains.kotlin.android")
}

android {
    namespace = "expo.modules.kritha.feature.onnx"
    compileSdk = rootProject.ext.compileSdkVersion
    defaultConfig { minSdk = rootProject.ext.minSdkVersion }
}

dependencies {
    implementation(project(":app"))
    implementation(project(":kritha"))
}

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
  kotlinOptions {
    freeCompilerArgs += ["-Xskip-metadata-version-check"]
  }
}
