plugins {
    id("com.android.dynamic-feature")
    id("org.jetbrains.kotlin.android")
}

android {
    namespace = "expo.modules.kritha.feature.onnx"
    compileSdk = rootProject.ext.compileSdkVersion
    defaultConfig {
      minSdk = rootProject.ext.minSdkVersion
    }
}

dependencies {
    implementation(project(":app"))
    implementation(project(":kritha"))
    implementation("com.microsoft.onnxruntime:onnxruntime-android:1.20.0")
}

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
  kotlinOptions {
    freeCompilerArgs += ["-Xskip-metadata-version-check"]
  }
}
