plugins {
    id("com.android.dynamic-feature")
    id("org.jetbrains.kotlin.android")
}

android {
    namespace = "expo.modules.kritha.feature.litert"
    compileSdk = rootProject.ext.compileSdkVersion

    defaultConfig {
        minSdk = rootProject.ext.minSdkVersion
    }
}

dependencies {
    implementation(project(":app"))
    implementation(project(":kritha"))
    implementation("com.google.ai.edge.litert:litert:2.2.0") {
        exclude group: "com.google.android.play", module: "ai-delivery"
    }
}

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
  kotlinOptions {
    freeCompilerArgs += ["-Xskip-metadata-version-check"]
  }
}
